// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yLKqVQnoakivvqF6AfJ-_ztBQ3n2GUg',
    appId: '1:674023205180:web:18058b9df479005a851639',
    messagingSenderId: '674023205180',
    projectId: 'ayo-belanja-7bc1e',
    authDomain: 'ayo-belanja-7bc1e.firebaseapp.com',
    databaseURL: 'https://ayo-belanja-7bc1e.firebaseio.com',
    storageBucket: 'ayo-belanja-7bc1e.appspot.com',
    measurementId: 'G-0W0Y5B2EVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4WmeqwlzDRvYS9sLcaRDnoJDQWVgeCI',
    appId: '1:674023205180:android:f308685cf8fe401d851639',
    messagingSenderId: '674023205180',
    projectId: 'ayo-belanja-7bc1e',
    databaseURL: 'https://ayo-belanja-7bc1e.firebaseio.com',
    storageBucket: 'ayo-belanja-7bc1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_z_ydOKUJOHHDgaI_2IJwZ_lpTXKQ-js',
    appId: '1:674023205180:ios:8a850a14469c0f17851639',
    messagingSenderId: '674023205180',
    projectId: 'ayo-belanja-7bc1e',
    databaseURL: 'https://ayo-belanja-7bc1e.firebaseio.com',
    storageBucket: 'ayo-belanja-7bc1e.appspot.com',
    androidClientId: '674023205180-0i7h7jvfv2d0a4j9ivlll7uj063mhh4a.apps.googleusercontent.com',
    iosClientId: '674023205180-cic46aftoibd641k8jdhhecam1ktvigc.apps.googleusercontent.com',
    iosBundleId: 'com.gocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_z_ydOKUJOHHDgaI_2IJwZ_lpTXKQ-js',
    appId: '1:674023205180:ios:8a850a14469c0f17851639',
    messagingSenderId: '674023205180',
    projectId: 'ayo-belanja-7bc1e',
    databaseURL: 'https://ayo-belanja-7bc1e.firebaseio.com',
    storageBucket: 'ayo-belanja-7bc1e.appspot.com',
    androidClientId: '674023205180-0i7h7jvfv2d0a4j9ivlll7uj063mhh4a.apps.googleusercontent.com',
    iosClientId: '674023205180-cic46aftoibd641k8jdhhecam1ktvigc.apps.googleusercontent.com',
    iosBundleId: 'com.gocery',
  );
}
